name: easy_box
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  equatable: ^2.0.7
  go_router: ^16.2.1
  intl: ^0.20.2
  mobile_scanner: ^5.1.0
  shared_preferences: ^2.5.3
  collection: ^1.19.1
  dartz: ^0.10.1
  sqflite: ^2.4.2
  path_provider: ^2.1.5
  path: ^1.9.1
  connectivity_plus: ^6.1.5
  image_picker: ^1.2.0
  uuid: ^4.5.1
  cached_network_image: ^3.3.1
  dio: ^5.5.0+1
  talker_dio_logger: ^4.1.1
  talker_flutter: ^4.2.3
  talker_bloc_logger: ^4.1.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: any
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  generate: true

  uses-material-design: true

  assets:
    - designs/

