# Generated by Django 4.2.24 on 2025-09-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
