version: '3.8'

services:
  api:
    image: 321654neo/easy_box_backend:latest
    restart: always
    command: bash -c "python manage.py migrate --noinput && gunicorn backend.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - db_data:/app/db
    ports:
      - "8000:8000"
    env_file:
      - ./.env

volumes:
  db_data:
