name: Build and Notify on Develop Merge

on:
  push:
    branches:
      - develop

jobs:
  build-and-send-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          dart-version: '3.8.1'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Send APK to Telegram
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 New merge into 'develop' branch!
            
            Commit by: ${{ github.actor }}
            Message: 
            ${{ github.event.head_commit.message }}
            
            See commit: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
          document: "build/app/outputs/flutter-apk/app-release.apk"