name: SSH Test

on:
  workflow_dispatch: # запуск вручную

jobs:
  test-ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Debug SSH key (first lines)
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | head -5

      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          debug: true
          script: |
            echo "✅ Успешное подключение к серверу!"
            hostname
            whoami
